### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by Shreyanand**
@codificat is this editable?

### CODE REVIEW

**Comment by codificat** [comment]
> @codificat is this editable?

Yes, this works now, thanks!

I just pushed some suggested changes, basically expanding the LLM section a bit.

**Comment by codificat** [comment]
Also updated the [wip version on hackmd](https://hackmd.io/D08wsIlKSC2wMYMjxB53TA) in case you find it easier to collaborate there

**Comment by Shreyanand** [comment]
Added a readme for the notebooks directory as well. We can merge it if it looks good at this point.

**Comment by codificat** [comment]
Thanks!  I expanded the notebooks README to include the recently-merged haystack notebook as well, and add some links.

Going to merge

**Review by codificat — APPROVED** [review]

**Pull request merged**
