### PR TITLE
Notebook to create comparison data

### PR DESCRIPTION
**Pull request by suppathak**
#58

### CODE REVIEW

**Review by Shreyanand — COMMENTED** [review]
This is cool! 💯 Let me add the Argilla how to use notebook that shows how to access the instance on our cluster and with that added we can update and merge this.

**Comment by suppathak** [comment]
> This is cool! 💯 Let me add the Argilla how to use notebook that shows how to access the instance on our cluster and with that added we can update and merge this.

Perfect! Thank you. :+1:

**Review by Shreyanand — CHANGES_REQUESTED** [review]
💯 The notebook adds dataset templates for Argilla feedback collection. It will be updated with rlhf workflow once we have that data.

* Change the notebook location to be feedback/create-comparison-data.ipynb (remove the rlhf directory)
* Add a small description in the README.md file
* Update the notebook title to "Collect application feedback using Argilla"

**Review by Shreyanand — APPROVED** [review]
Looks good 👍

**Pull request merged**
